import { env as processEnv } from 'node:process'

export interface ServerEnv {
  __VF_PROJECT_AI_SERVER_HOST__: string
  __VF_PROJECT_AI_SERVER_PORT__: number
  __VF_PROJECT_AI_SERVER_WS_PATH__: string
  __VF_PROJECT_AI_SERVER_DATA_DIR__: string
  __VF_PROJECT_AI_SERVER_LOG_DIR__: string
  __VF_PROJECT_AI_SERVER_LOG_LEVEL__: 'debug' | 'info' | 'warn' | 'error'
  __VF_PROJECT_AI_SERVER_ALLOW_CORS__: boolean
  __VF_PROJECT_AI_CLIENT_MODE__?: 'dev' | 'static'
  __VF_PROJECT_AI_CLIENT_BASE__?: string
  __VF_PROJECT_AI_CLIENT_DIST_PATH__?: string
  __VF_PROJECT_AI_ADAPTER_CLAUDE_CODE_CLI_PATH__?: string
  __VF_PROJECT_AI_ADAPTER_CLAUDE_CODE_CLI_ARGS__?: string
}

export function loadEnv(): ServerEnv {
  const {
    __VF_PROJECT_AI_SERVER_HOST__ = 'localhost',
    __VF_PROJECT_AI_SERVER_PORT__ = '8787',
    __VF_PROJECT_AI_SERVER_WS_PATH__ = '/ws',
    __VF_PROJECT_AI_SERVER_DATA_DIR__ = '.data',
    __VF_PROJECT_AI_SERVER_LOG_DIR__ = '.logs',
    __VF_PROJECT_AI_SERVER_LOG_LEVEL__ = 'info',
    __VF_PROJECT_AI_SERVER_ALLOW_CORS__,
    __VF_PROJECT_AI_CLIENT_MODE__ = 'static',
    __VF_PROJECT_AI_CLIENT_BASE__,
    __VF_PROJECT_AI_CLIENT_DIST_PATH__,

    __VF_PROJECT_AI_ADAPTER_CLAUDE_CODE_CLI_PATH__,
    __VF_PROJECT_AI_ADAPTER_CLAUDE_CODE_CLI_ARGS__
  } = processEnv || {}
  return {
    __VF_PROJECT_AI_SERVER_HOST__,
    __VF_PROJECT_AI_SERVER_PORT__: Number(__VF_PROJECT_AI_SERVER_PORT__),
    __VF_PROJECT_AI_SERVER_WS_PATH__,
    __VF_PROJECT_AI_SERVER_DATA_DIR__,
    __VF_PROJECT_AI_SERVER_LOG_DIR__,
    __VF_PROJECT_AI_SERVER_LOG_LEVEL__:
      __VF_PROJECT_AI_SERVER_LOG_LEVEL__ as ServerEnv['__VF_PROJECT_AI_SERVER_LOG_LEVEL__'],
    __VF_PROJECT_AI_SERVER_ALLOW_CORS__: __VF_PROJECT_AI_SERVER_ALLOW_CORS__ != null
      ? __VF_PROJECT_AI_SERVER_ALLOW_CORS__ === 'true'
      : true,
    __VF_PROJECT_AI_CLIENT_MODE__:
      __VF_PROJECT_AI_CLIENT_MODE__ as ServerEnv['__VF_PROJECT_AI_CLIENT_MODE__'],
    __VF_PROJECT_AI_CLIENT_BASE__,
    __VF_PROJECT_AI_CLIENT_DIST_PATH__,

    __VF_PROJECT_AI_ADAPTER_CLAUDE_CODE_CLI_PATH__,
    __VF_PROJECT_AI_ADAPTER_CLAUDE_CODE_CLI_ARGS__
  }
}
